# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: cloudquery-postgres

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: cloudquery-postgres
  type: postgres
  url: localhost:5432
  database: cloudquery
  user: cloudquery
  secureJsonData:
    password: cloudquery
  jsonData:
    sslmode: "disable"